### ISSUE TITLE
Python 3 error in mapgenomes

### ISSUE THREAD

**Issue by cazzlewazzle89** [compmetagen/strainest#1]
I have encountered the following error when using the mapgenomes function

```
Traceback (most recent call last):
  File "/shared/software/anaconda3/bin/strainest", line 11, in <module>
    load_entry_point('strainest==1.2', 'console_scripts', 'strainest')()
  File "/shared/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/shared/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/shared/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/shared/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/shared/software/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/shared/software/anaconda3/lib/python3.6/site-packages/strainest/scripts/strainest_cmd.py", line 56, in mapgenomes
    record = strainest.api.mapgenome(genome, reference, mapped)
  File "/shared/software/anaconda3/lib/python3.6/site-packages/strainest/api/_mapgenome.py", line 80, in mapgenome
    mar = strainest.mummer.MummerAlignmentReader(align_handler)
  File "/shared/software/anaconda3/lib/python3.6/site-packages/strainest/mummer.py", line 37, in __init__
    if line.startswith('-- Alignments between'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```
I have tried running the command using both python 2.7 and 3.6 to no avail.

Do you have any suggestions on how to solve this?

Thanks,

Calum

**Comment by davidealbanese** [comment]
Dear @cazzlewazzle89,
this problem seems to be related to Python 3. I'll look into this soon. In the meanwhile you can use the Docker distribution.

Thanks, 
Davide

**Comment by cazzlewazzle89** [comment]
Thanks Davide.

No luck with the Docker version either I'm afraid. Running into the following error while using Docker Toolbox.

Calum

```
root@925ad6e46b3e:/strainest# strainest mapgenomes GCF_000236475.fna GCF_000284735.fna GCF_000006865.fna alignment
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
  [##################------------------]   50%
Traceback (most recent call last):
  File "/usr/local/bin/strainest", line 11, in <module>
    load_entry_point('strainest==1.2.2', 'console_scripts', 'strainest')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/strainest/scripts/strainest_cmd.py", line 56, in mapgenomes
    record = strainest.api.mapgenome(genome, reference, mapped)
  File "/usr/local/lib/python2.7/dist-packages/strainest/api/_mapgenome.py", line 45, in mapgenome
    proc = subprocess.Popen(cmd, stdout=devnull, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by davidealbanese** [comment]
Dear Calum,
could you put the output of `ls -al`?

2018-01-29 15:09 GMT+01:00 Calum Walsh <notifications@github.com>:

**Comment by cazzlewazzle89** [comment]
```
root@41a55c83603b:/strainest# ls -al
total 7404
drwxrwxrwx  1 1000 staff    4096 Jan 29 13:59 .
drwxr-xr-x 41 root root     4096 Jan 29 14:31 ..
-rwxrwxrwx  1 1000 staff 2399466 Jan 29 13:57 GCF_000006865.fna
-rwxrwxrwx  1 1000 staff 2609733 Jan 29 13:25 GCF_000236475.fna
-rwxrwxrwx  1 1000 staff 2556546 Jan 29 13:50 GCF_000284735.fna
-rwxrwxrwx  1 1000 staff       0 Jan 29 14:31 alignment
```

**Comment by davidealbanese** [comment]
Dear @cazzlewazzle89, the Docker image should be fixed now. Remember to update the image before running it with:
```sh
docker pull compmetagen/strainest
```

Let me know if it works,
Davide

**Comment by cazzlewazzle89** [comment]
Thanks Davide, that fixed that issue but there is a different one happening now 

`root@b5d68a662bf5:/strainest# strainest mapgenomes GCF_000236475.fna GCF_000284735.fna GCF_000006865.fna alignment.fna
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
  [##################------------------]   50%
Traceback (most recent call last):
  File "/usr/local/bin/strainest", line 11, in <module>
    load_entry_point('strainest==1.2.2', 'console_scripts', 'strainest')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/strainest/scripts/strainest_cmd.py", line 56, in mapgenomes
    record = strainest.api.mapgenome(genome, reference, mapped)
  File "/usr/local/lib/python2.7/dist-packages/strainest/api/_mapgenome.py", line 73, in mapgenome
    os.remove(align_fn)
OSError: [Errno 26] Text file busy: 'alignment.fna.align'`

Do you have an example dataset available that I could try to rule out the possibility that it is my data that is causing the issue?

Calum

**Comment by cazzlewazzle89** [comment]
Thanks Davide,

That fixed the issue but there is another one presenting itself now.

`root@b5d68a662bf5:/strainest# strainest mapgenomes GCF_000236475.fna GCF_000284735.fna GCF_000006865.fna alignment.fna
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
  [##################------------------]   50%
Traceback (most recent call last):
  File "/usr/local/bin/strainest", line 11, in <module>
    load_entry_point('strainest==1.2.2', 'console_scripts', 'strainest')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/strainest/scripts/strainest_cmd.py", line 56, in mapgenomes
    record = strainest.api.mapgenome(genome, reference, mapped)
  File "/usr/local/lib/python2.7/dist-packages/strainest/api/_mapgenome.py", line 73, in mapgenome
    os.remove(align_fn)
OSError: [Errno 26] Text file busy: 'alignment.fna.align'`

Do you have an example dataset that I could try to rule out the possibility that it is my data that is causing the issue?

Calum

**Comment by davidealbanese** [comment]
This error should be fixed now. Remember to update the image before running it.

Let me know,
Davide

**Comment by cazzlewazzle89** [comment]
Thanks Davide,
That appears to be working now. Although I got an error further downstream with the snpdist command

```
root@55dca971591e:/strainest# strainest snpdist snp.dgrp snp_dist.txt hist.pdf
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
  [------------------------------------]    0%/usr/local/lib/python2.7/dist-packages/strainest/api/_snpdist.py:37: RuntimeWarning: invalid value encountered in long_scalars
  d = np.sum(snp.iloc[:, i] != snp.iloc[:, j]) / snp.shape[0]
  [####################################]  100%
Traceback (most recent call last):
  File "/usr/local/bin/strainest", line 11, in <module>
    load_entry_point('strainest==1.2.2', 'console_scripts', 'strainest')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/strainest/scripts/strainest_cmd.py", line 109, in snpdist
    strainest.api.snpdist(snp, dist, hist)
  File "/usr/local/lib/python2.7/dist-packages/strainest/api/_snpdist.py", line 45, in snpdist
    plt.hist(squareform(dist), bins=100)
  File "/usr/lib/python2.7/dist-packages/scipy/spatial/distance.py", line 1494, in squareform
    is_valid_dm(X, throw=True, name='X')
  File "/usr/lib/python2.7/dist-packages/scipy/spatial/distance.py", line 1577, in is_valid_dm
    'symmetric.') % name)
ValueError: Distance matrix 'X' must be symmetric.
```

I think it may be caused by the output from map2snp as the output appears to just be a comma-separated list of the files used to generate the alignment in the previous step

```
root@55dca971591e:/strainest# cat snp.dgrp
NC_002662.1,Ref,GCF_000236475.fna,GCF_000284735.fna,GCF_000344575.fna,GCF_000442845.fna,GCF_000479375.fna,GCF_000488975.fna,GCF_000493355.fna,GCF_000703145.fna,GCF_000721865.fna,GCF_000731635.fna,GCF_000759595.fna,GCF_000761115.fna,GCF_000786755.fna,GCF_000807375.fna,GCF_001437565.fna,GCF_001456455.fna,GCF_001456475.fna,GCF_001456495.fna,GCF_001456505.fna,GCF_001456525.fna,GCF_001456545.fna,GCF_001456575.fna,GCF_001456595.fna,GCF_001456615.fna,GCF_001456625.fna,GCF_001456655.fna,GCF_001456675.fna,GCF_001456685.fna,GCF_001456695.fna,GCF_001456725.fna,GCF_001456755.fna,GCF_001456775.fna,GCF_001456785.fna,GCF_001456795.fna,GCF_001456835.fna,GCF_001456855.fna,GCF_001514475.fna,GCF_001540895.fna,GCF_001591725.fna,GCF_001622225.fna,GCF_001622235.fna,GCF_001622285.fna,GCF_001622365.fna,GCF_001672265.fna,GCF_001856165.fna,GCF_002078435.fna,GCF_002078475.fna,GCF_002078855.fna,GCF_002078975.fna,GCF_002078995.fna,GCF_002115705.fna,GCF_002563455.fna,GCF_002563475.fna,GCF_002563535.fna,GCF_002563575.fna,GCF_002563615.fna,GCF_900088425.fna,alignment.fna
```

**Comment by davidealbanese** [comment]
Dear Calum, it seems that there are no SNVs in your alignment file. Could you provide `GCF_000006865.fasta` and  `alignment.fna`?

**Comment by cazzlewazzle89** [comment]
Davide, the files are too large to upload here. I have added them to my google drive 

[https://drive.google.com/open?id=1LQ0xLbiblVYoDU9WDusW_l7_gtJ2zqkc](url)

Thanks, Calum

**Comment by davidealbanese** [comment]
Calum, the last entry of the `alignment.fna` FASTA is a near-empty sequence (called "alignment.fna") which causes the core genome and therefore the SNV matrix to be empty. Remove this sequence and the core genome will be of 1207059 nt.

Let me know,
Davide

**Comment by cazzlewazzle89** [comment]
That seems to have fixed all the issues.
Thanks for all the troubleshooting,

Calum

**Comment by davidealbanese** [comment]
Thank you, Calum!
