### ISSUE TITLE
error in strainest mapgenomes when preparing the reference

### ISSUE THREAD

**Issue by shitou-6** [compmetagen/strainest#12]
1. faced  ERROR1 when running "strainest mapgenomes R2.fna R3.fna R1.fna map.fna"(strainest was installed on CentOS Linux 7 (Core), Linux 3.10.0-957.27.2.el7.x86_64 ) 
2.  then faced ERROR2 when trying to solve the problem by reinstall strainest with docker just as davidealbanese said on page "https://github.com/compmetagen/strainest/issues/1"
--------------------------------------------------------------------------------------------------
ERROR1 report just as follows: 
(base) [zhurj@mnhead repfna]$ strainest mapgenomes R2.fna R3.fna R1.fna map.fna

Traceback (most recent call last):
  File "/home/zhurj/share/miniconda3/bin/strainest", line 11, in <module>
    load_entry_point('strainest==1.2.4', 'console_scripts', 'strainest')()
  File "/home/zhurj/share/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/zhurj/share/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/zhurj/share/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zhurj/share/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zhurj/share/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/zhurj/share/miniconda3/lib/python3.7/site-packages/strainest/scripts/strainest_cmd.py", line 56, in mapgenomes
    record = strainest.api.mapgenome(genome, reference, mapped)
  File "/home/zhurj/share/miniconda3/lib/python3.7/site-packages/strainest/api/_mapgenome.py", line 80, in mapgenome
    mar = strainest.mummer.MummerAlignmentReader(align_handler)
  File "/home/zhurj/share/miniconda3/lib/python3.7/site-packages/strainest/mummer.py", line 37, in __init__
    if line.startswith('-- Alignments between'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
---------------------------------------------------------------------------------------------
ERROR2 report as follows:
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
----------------------------------------------------------------------------------------------
Are there any other solutions to fix the probem? thanks very much

**Comment by shitou-6** [comment]
Problem solved
Errors are caused by python version, strainest installed with conda should be installed under env python2
