### ISSUE TITLE
count_coverage() takes at least 1 positional argument

### ISSUE THREAD

**Issue by palomo11** [compmetagen/strainest#3]
Hi,

Thanks for your reply on how to build your own database, I'm gonna try to do it but first I wanted to run the test provide with strainest, but when I have tried to run it:

strainest est P_acnes/snp_clust.dgrp reads.sorted.bam outputdir

I got the following error:

```
Traceback (most recent call last):
  File "/home/people/name/.conda/envs/strainest-env/bin/strainest", line 11, in <module>
    load_entry_point('strainest==1.2', 'console_scripts', 'strainest')()
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/strainest/scripts/strainest_cmd.py", line 180, in est
    threads)
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/strainest/api/_est.py", line 138, in est
    counts = get_counts(align, positions, quality_thr)
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/strainest/api/_est.py", line 47, in get_counts
    quality_threshold=quality_threshold)
  File "pysam/libcalignmentfile.pyx", line 1438, in pysam.libcalignmentfile.AlignmentFile.count_coverage
TypeError: count_coverage() takes at least 1 positional argument (0 given)
```

I have the following files in the folder:

90318631 Apr 10 15:15 reads.sam
30239759 Apr 10 15:15 reads.bam
28391376 Apr 10 15:15 reads.sorted.bam
   21760 Apr 10 15:15 reads.sorted.bam.bai

I also have:
head P_acnes/snp_clust.dgrp
NC_006085.1,Ref,GCF_000735065.1_PacnesHL201PA1v01_genomic.fna,GCF_000376705.1_ASM37670v1_genomic.fna,GCF_000144795.1_ASM14479v1_genomic.fna,GCF_000144105.1_ASM14410v1_genomic.fna,GCF_000194905.1_ASM19490v1_genomic.fna,GCF_001469615.1_ASM146961v1_genomic.fna,GCF_000145435.1_ASM14543v1_genomic.fna,GCF_001297145.1_ASM129714v1_genomic.fna,GCF_000144465.1_ASM14446v1_genomic.fna,GCF_000144325.1_ASM14432v1_genomic.fna,GCF_000145555.1_ASM14555v1_genomic.fna,GCF_000145535.1_ASM14553v1_genomic.fna,GCF_000735055.1_PacnesHL202PA1v1.0_genomic.fna,GCF_000240035.1_ASM24003v1_genomic.fna,GCF_000178075.1_ASM17807v1_genomic.fna,GCF_001469595.1_ASM146959v1_genomic.fna,GCF_000144005.1_ASM14400v1_genomic.fna,GCF_001660955.1_ASM166095v1_genomic.fna,GCF_000302515.1_ASM30251v1_genomic.fna,GCF_000144425.1_ASM14442v1_genomic.fna
22,A,C,A,A,C,A,A,A,C,C,A,A,A,C,A,A,A,C,A,A,A
50,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,T,A
60,G,A,G,G,A,G,G,G,A,A,G,G,G,A,G,G,G,A,G,G,G
68,C,T,C,C,T,C,C,C,T,T,C,C,C,T,C,C,C,T,C,C,C
80,T,C,T,T,T,T,T,T,C,T,T,T,T,T,T,T,T,T,T,T,T
83,G,A,G,G,A,G,G,G,A,A,G,G,G,A,G,G,G,A,G,G,G
92,T,C,T,T,T,T,T,T,C,T,T,T,T,T,T,T,T,T,T,T,T
100,G,G,A,G,G,G,G,A,G,G,G,G,G,G,G,G,G,G,G,G,A
103,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T

Do you know what is going on?

Thank you very much in advance.

**Comment by davidealbanese** [comment]
Dear @palomo11,
the new StrainEst release (1.2.3) works with pysam >=0.12 and the problem should be resolved.

Let me know,
Davide
