### ISSUE TITLE
DeprecationWarning error

### ISSUE THREAD

**Issue by sacl07** [compmetagen/strainest#4]
Hi, I got the following error message when running the test code `strainest est P_acnes/snp_clust.dgrp reads.sorted.bam outputdir`

/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "/usr/local/bin/strainest", line 11, in <module>
    load_entry_point('strainest==1.2', 'console_scripts', 'strainest')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/strainest/scripts/strainest_cmd.py", line 180, in est
    threads)
  File "/usr/local/lib/python2.7/dist-packages/strainest/api/_est.py", line 138, in est
    counts = get_counts(align, positions, quality_thr)
  File "/usr/local/lib/python2.7/dist-packages/strainest/api/_est.py", line 47, in get_counts
    quality_threshold=quality_threshold)
  File "pysam/libcalignmentfile.pyx", line 1438, in pysam.libcalignmentfile.AlignmentFile.count_coverage
TypeError: count_coverage() takes at least 1 positional argument (0 given)

How can I fix it? Thank you.

**Comment by davidealbanese** [comment]
Fixed in StrainEst 1.2.4.

Thank you,
Davide
