### ISSUE TITLE
operands could not be broadcast

### ISSUE THREAD

**Issue by palomo11** [compmetagen/strainest#5]
Hi 

I have tried to run it again with the new version 1.1.3 and now I get a different error:

strainest est P_acnes/snp_clust.dgrp reads.sorted.bam outputdir

```
Traceback (most recent call last):
  File "/home/people/name/.conda/envs/strainest-env/bin/strainest", line 11, in <module>
    load_entry_point('strainest==1.2.2', 'console_scripts', 'strainest')()
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/strainest/scripts/strainest_cmd.py", line 180, in est
    threads)
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/strainest/api/_est.py", line 138, in est
    counts = get_counts(align, positions, quality_thr)
  File "/home/people/name/.conda/envs/strainest-env/lib/python2.7/site-packages/strainest/api/_est.py", line 48, in get_counts
    counts[:, i] += np.asarray(ref_count, dtype=np.int64).flatten()
ValueError: operands could not be broadcast together with shapes (4,) (10240976,) (4,) 
```

**Comment by davidealbanese** [comment]
Fixed in StrainEst 1.2.4.

Thank you,
Davide
